all:
  children:
    webservers:
      hosts:
        web1.domain.com
        web2.domain.com
    dbservers:
      hosts:
        db1.domain.com
        db2.domain.com




# Example inventory in INI format

#[webservers]
#web1.domain.com
#web2.domain.com

#[dbservers]
#db1.domain.com
#db2.domain.com


