all:
  children:
    webservers: #web server group
      children:
        hosts:
          web_server_in:  #server group
            web1.domain.com
          web_server_uk:  #server group
            web2.domain.com
    dbservers: #db server group
      children:
        hosts:
          db_server_in:
            db1.domain.com
          db_server_uk:
            db2.domain.com


# Example inventory with Parent-Child relationships

#[webservers:children]
#webservers_in
#webservers_uk

#[webservers_in]
#web1.domain.com
#web2.domain.com

#[webservers_uk]
#web3.domain.com
#web4.domain.com