

#Playbook.yml
-
  name: ADD

#Variables use Jinja2 templating

- name: Access Dictionay Variable Playbook.yml
  ...

  tasks:
    - name: Diaplay the entire user dictonary #Variables
      debug:
        car: user
    
    - name: Access specific  values in the dictronary
      debug:
        msg: "Username : {{ user.name }}, Password:{{ user.password }}"    # without quotes

    - name: Display the first package
      debug:
        msg: "The third package is {{ packages[2] }}" # specific item in a list

    - name: Install packages using package manager
      becomre: true
      debug:
        msg: "Installing package {{ item }} "
      loop: "{{ packages }}"  #Entire list


#-----------------------------


/etc/ansible/hosts
web1 ansible_host=171.20.1.100
web1 ansible_host=171.20.1.101 dns_server=10.5.5.4  #host level variable
web1 ansible_host=171.20.1.102

[web_servers]  #group name
web1
web2
web3

[web_servers:vars]  #group level variable
dns_server=10.5.5.3



- name: check /etc/ansible/hosts file
  hosts: all
  tasks:
    - shell: cat /etc/ansible/hosts   #shell module
      register: result                #register directive

    - debug:        #print the previous command output
      var: result
      #var: result.rc  #only the return code
      #var: result.stdout  #only the output


#ansible-playbook playbook.yml --extra-vars "ntp_server=10.1.1.1"


## hostvars['web2'].ansible_host 

#Facts

hostvars['web2'].ansible_facts.architecture


hostvars['web2'].ansible_facts.mount
hostvars['web2'].['ansible_facts'].['mount']


